# Generated by Django 5.0.4 on 2024-06-08 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_id', models.IntegerField(null=True)),
                ('match_date', models.DateTimeField(null=True)),
                ('match_timestamp', models.IntegerField(null=True)),
                ('match_periods_first', models.CharField(max_length=250, null=True)),
                ('match_periods_second', models.CharField(max_length=250, null=True)),
                ('match_venue_name', models.CharField(max_length=250, null=True)),
                ('match_venue_city', models.CharField(max_length=250, null=True)),
                ('match_status_long', models.CharField(max_length=250, null=True)),
                ('league_id', models.CharField(max_length=250, null=True)),
                ('league_name', models.CharField(max_length=100, null=True)),
                ('league_country', models.CharField(max_length=250, null=True)),
                ('league_logo', models.URLField(max_length=250, null=True)),
                ('league_flag', models.URLField(max_length=250, null=True)),
                ('league_season', models.IntegerField(null=True)),
                ('league_round', models.CharField(max_length=100, null=True)),
                ('home_team_name', models.CharField(max_length=250, null=True)),
                ('home_team_logo', models.URLField(max_length=250, null=True)),
                ('home_team_winner', models.CharField(max_length=250, null=True)),
                ('away_team_name', models.CharField(max_length=250, null=True)),
                ('away_team_logo', models.URLField(max_length=250, null=True)),
                ('away_team_winner', models.CharField(max_length=250, null=True)),
                ('home_team_goals', models.IntegerField(null=True)),
                ('away_team_goals', models.IntegerField(null=True)),
                ('halftime_score', models.CharField(max_length=250, null=True)),
                ('fulltime_score', models.CharField(max_length=250, null=True)),
                ('extratime_score', models.CharField(max_length=250, null=True)),
                ('penalty_score', models.CharField(max_length=250, null=True)),
                ('match_refree', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchesEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('player_name', models.CharField(blank=True, max_length=100, null=True)),
                ('assist_id', models.CharField(blank=True, max_length=100, null=True)),
                ('assist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('detail', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('fixture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchesLineUps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('team_color', models.JSONField(blank=True, null=True)),
                ('coach_id', models.IntegerField(blank=True, null=True)),
                ('coach_name', models.CharField(blank=True, max_length=100, null=True)),
                ('coach_photo', models.URLField(blank=True, null=True)),
                ('formation', models.CharField(blank=True, max_length=100, null=True)),
                ('startXI', models.JSONField(blank=True, null=True)),
                ('substitutes', models.JSONField(blank=True, max_length=100, null=True)),
                ('fixture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchesPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('update', models.CharField(blank=True, max_length=100, null=True)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('player_name', models.CharField(blank=True, max_length=100, null=True)),
                ('player_photo', models.URLField(blank=True, null=True)),
                ('player_statistics', models.JSONField(blank=True, null=True)),
                ('fixture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics_data', models.JSONField(blank=True, null=True)),
                ('fixture_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
    ]
