# Generated by Django 5.0.4 on 2024-04-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='fulltime_score',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
