# Generated by Django 5.0.4 on 2024-05-13 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchesEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('player_name', models.CharField(blank=True, max_length=100, null=True)),
                ('assist_id', models.CharField(blank=True, max_length=100, null=True)),
                ('assist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('detail', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('fixture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
    ]
