# Generated by Django 5.0.4 on 2024-05-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('team_code', models.CharField(blank=True, max_length=100, null=True)),
                ('team_country', models.CharField(blank=True, max_length=100, null=True)),
                ('team_founded', models.CharField(blank=True, max_length=100, null=True)),
                ('team_national', models.BooleanField(blank=True, max_length=100, null=True)),
                ('team_logo', models.URLField(blank=True, null=True)),
                ('venue_id', models.CharField(blank=True, max_length=100, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=100, null=True)),
                ('venue_address', models.CharField(blank=True, max_length=100, null=True)),
                ('venue_city', models.CharField(blank=True, max_length=100, null=True)),
                ('venue_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('venue_image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
