# Generated by Django 5.0.4 on 2024-06-02 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField(blank=True, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('team', models.JSONField(blank=True, null=True)),
                ('venue', models.JSONField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.JSONField(blank=True, max_length=100, null=True)),
                ('league', models.JSONField(blank=True, null=True)),
                ('form', models.CharField(blank=True, max_length=200, null=True)),
                ('fixtures', models.JSONField(blank=True, null=True)),
                ('goals', models.JSONField(blank=True, max_length=100, null=True)),
                ('biggest', models.JSONField(blank=True, max_length=100, null=True)),
                ('clean_sheet', models.JSONField(blank=True, null=True)),
                ('failed_to_score', models.JSONField(blank=True, max_length=100, null=True)),
                ('penalty', models.JSONField(blank=True, max_length=100, null=True)),
                ('lineups', models.JSONField(blank=True, max_length=100, null=True)),
                ('cards', models.JSONField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayersInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(blank=True, null=True)),
                ('player', models.JSONField(blank=True, null=True)),
                ('statistics', models.JSONField(blank=True, max_length=100, null=True)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teaminformation')),
            ],
        ),
    ]
