# Generated by Django 5.0.4 on 2024-06-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playersinformation',
            old_name='team_id',
            new_name='team',
        ),
    ]
