# Generated by Django 5.0.4 on 2024-05-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField(blank=True, null=True)),
                ('league_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.URLField(blank=True, max_length=100, null=True)),
                ('flag', models.URLField(blank=True, max_length=100, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('team_logo', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='teaminformation',
            name='league_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teaminformation',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
