# Generated by Django 5.0.4 on 2024-05-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teamstatistics_teaminformation_league_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminformation',
            name='team_code',
        ),
        migrations.RemoveField(
            model_name='teaminformation',
            name='team_country',
        ),
        migrations.RemoveField(
            model_name='teaminformation',
            name='team_founded',
        ),
        migrations.RemoveField(
            model_name='teaminformation',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='teaminformation',
            name='team_logo',
        ),
        migrations.RemoveField(
            model_name='teaminformation',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='teaminformation',
            name='team_national',
        ),
        migrations.RemoveField(
            model_name='teaminformation',
            name='venue_address',
        ),
        migrations.RemoveField(
            model_name='teaminformation',
            name='venue_capacity',
        ),
        migrations.RemoveField(
            model_name='teaminformation',
            name='venue_city',
        ),
        migrations.RemoveField(
            model_name='teaminformation',
            name='venue_id',
        ),
        migrations.RemoveField(
            model_name='teaminformation',
            name='venue_image',
        ),
        migrations.RemoveField(
            model_name='teaminformation',
            name='venue_name',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='country',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='league_id',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='league_name',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='season',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='team_logo',
        ),
        migrations.RemoveField(
            model_name='teamstatistics',
            name='team_name',
        ),
        migrations.AddField(
            model_name='teaminformation',
            name='team',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teaminformation',
            name='venue',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='biggest',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='cards',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='clean_sheet',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='failed_to_score',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='fixtures',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='goals',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='league',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='lineups',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='penalty',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='team',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
    ]
