# Generated by Django 5.0.4 on 2024-05-25 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت '),
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='status',
            field=models.CharField(choices=[('draft', 'آماده انتشار'), ('published', 'منتشر شده')], default='draft', max_length=60, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
