# Generated by Django 5.0.4 on 2024-05-14 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixturesLineUps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('team_color', models.JSONField(blank=True, null=True)),
                ('coach_id', models.IntegerField(blank=True, null=True)),
                ('coach_name', models.CharField(blank=True, max_length=100, null=True)),
                ('coach_photo', models.URLField(blank=True, null=True)),
                ('formation', models.CharField(blank=True, max_length=100, null=True)),
                ('startXI', models.JSONField(blank=True, null=True)),
                ('substitutes', models.JSONField(blank=True, max_length=100, null=True)),
                ('fixture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.fixtures')),
            ],
        ),
    ]
