# Generated by Django 5.0.4 on 2024-05-07 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_fixtures_fixture_referee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics_data', models.JSONField(blank=True, null=True)),
                ('fixture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.fixtures')),
            ],
        ),
    ]
