# Generated by Django 5.0.4 on 2024-05-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_fixturesplayerstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixturesplayerstats',
            name='player_statistics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
