# Generated by Django 5.0.4 on 2024-09-27 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShotsOnGoal', models.IntegerField(blank=True, null=True)),
                ('ShotsOffGoal', models.IntegerField(blank=True, null=True)),
                ('ShotsInsideBox', models.IntegerField(blank=True, null=True)),
                ('ShotsOutsideBox', models.IntegerField(blank=True, null=True)),
                ('TotalShots', models.IntegerField(blank=True, null=True)),
                ('BlockedShots', models.IntegerField(blank=True, null=True)),
                ('Fouls', models.IntegerField(blank=True, null=True)),
                ('CornerKicks', models.IntegerField(blank=True, null=True)),
                ('Offsides', models.IntegerField(blank=True, null=True)),
                ('BallPossession', models.CharField(blank=True, max_length=10, null=True)),
                ('YellowCards', models.IntegerField(blank=True, null=True)),
                ('RedCards', models.IntegerField(blank=True, null=True)),
                ('GoalkeeperSaves', models.IntegerField(blank=True, null=True)),
                ('Totalpasses', models.IntegerField(blank=True, null=True)),
                ('Passesaccurate', models.IntegerField(blank=True, null=True)),
                ('PassesPercent', models.CharField(blank=True, max_length=10, null=True)),
                ('ExpectedGoals', models.FloatField(blank=True, null=True)),
                ('GoalsPrevented', models.IntegerField(blank=True, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.leagueteams')),
            ],
        ),
    ]
