# Generated by Django 5.0.4 on 2025-06-12 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixturelineup',
            name='start_xi',
        ),
        migrations.RemoveField(
            model_name='fixturelineup',
            name='substitutes',
        ),
        migrations.AlterField(
            model_name='fixturelineup',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.coach'),
        ),
        migrations.AlterField(
            model_name='fixturelineup',
            name='formation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Attacker', 'Attacker'), (None, 'Unknown')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FixtureLineupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starting', models.BooleanField()),
                ('pos', models.CharField(blank=True, max_length=2, null=True)),
                ('grid', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('fixture_lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_players', to='league.fixturelineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
            ],
        ),
    ]
