# Generated by Django 5.0.4 on 2025-02-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
