# Generated by Django 5.0.4 on 2025-02-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_table_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
