# Generated by Django 5.0.4 on 2024-10-06 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_fixtureevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('faName', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=500, null=True)),
                ('birth_faPlace', models.CharField(blank=True, max_length=500, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=500, null=True)),
                ('birth_faCountry', models.CharField(blank=True, max_length=500, null=True)),
                ('nationality', models.CharField(blank=True, max_length=500, null=True)),
                ('faNationality', models.CharField(blank=True, max_length=500, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('career', models.JSONField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.leagueteams')),
            ],
        ),
        migrations.CreateModel(
            name='FixtureLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_color', models.JSONField(blank=True, null=True)),
                ('formation', models.CharField(max_length=50)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.coach')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.fixture')),
                ('start_xi', models.ManyToManyField(blank=True, related_name='start_xi', to='league.player')),
                ('substitutes', models.ManyToManyField(blank=True, related_name='substitutes', to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.leagueteams')),
            ],
        ),
    ]
