# Generated by Django 5.0.4 on 2025-06-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_remove_fixturelineup_start_xi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtureplayer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixtureplayer',
            name='offsides',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixtureplayer',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
