# Generated by Django 5.0.4 on 2024-10-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_coach_fixturelineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='grid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
