# Generated by Django 5.0.4 on 2025-02-13 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_table_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(blank=True, max_length=500, null=True)),
                ('fixtures_played_home', models.IntegerField(default=0)),
                ('fixtures_played_away', models.IntegerField(default=0)),
                ('fixtures_played_total', models.IntegerField(default=0)),
                ('wins_home', models.IntegerField(default=0)),
                ('wins_away', models.IntegerField(default=0)),
                ('wins_total', models.IntegerField(default=0)),
                ('draws_home', models.IntegerField(default=0)),
                ('draws_away', models.IntegerField(default=0)),
                ('draws_total', models.IntegerField(default=0)),
                ('losses_home', models.IntegerField(default=0)),
                ('losses_away', models.IntegerField(default=0)),
                ('losses_total', models.IntegerField(default=0)),
                ('goals_for_home', models.IntegerField(default=0)),
                ('goals_for_away', models.IntegerField(default=0)),
                ('goals_for_total', models.IntegerField(default=0)),
                ('goals_against_home', models.IntegerField(default=0)),
                ('goals_against_away', models.IntegerField(default=0)),
                ('goals_against_total', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
        ),
    ]
