# Generated by Django 5.0.4 on 2024-10-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_player_grid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixturePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('captain', models.BooleanField(default=False)),
                ('substitute', models.BooleanField(default=False)),
                ('shots_total', models.IntegerField(blank=True, null=True)),
                ('shots_on', models.IntegerField(blank=True, null=True)),
                ('goals_total', models.IntegerField(blank=True, null=True)),
                ('goals_conceded', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('saves', models.IntegerField(blank=True, null=True)),
                ('passes_total', models.IntegerField(blank=True, null=True)),
                ('passes_key', models.IntegerField(blank=True, null=True)),
                ('passes_accuracy', models.CharField(blank=True, max_length=10, null=True)),
                ('tackles_total', models.IntegerField(blank=True, null=True)),
                ('blocks', models.IntegerField(blank=True, null=True)),
                ('interceptions', models.IntegerField(blank=True, null=True)),
                ('duels_total', models.IntegerField(blank=True, null=True)),
                ('duels_won', models.IntegerField(blank=True, null=True)),
                ('dribbles_attempts', models.IntegerField(blank=True, null=True)),
                ('dribbles_success', models.IntegerField(blank=True, null=True)),
                ('dribbles_past', models.IntegerField(blank=True, null=True)),
                ('fouls_drawn', models.IntegerField(blank=True, null=True)),
                ('fouls_committed', models.IntegerField(blank=True, null=True)),
                ('cards_yellow', models.IntegerField(blank=True, null=True)),
                ('cards_yellow_red', models.IntegerField(blank=True, null=True)),
                ('cards_red', models.IntegerField(blank=True, null=True)),
                ('penalty_won', models.IntegerField(blank=True, null=True)),
                ('penalty_commited', models.IntegerField(blank=True, null=True)),
                ('penalty_scored', models.IntegerField(blank=True, null=True)),
                ('penalty_missed', models.IntegerField(blank=True, null=True)),
                ('penalty_saved', models.IntegerField(blank=True, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.leagueteams')),
            ],
        ),
    ]
