# Generated by Django 5.0.4 on 2025-02-19 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_teamstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstat',
            name='clean_sheet_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstat',
            name='clean_sheet_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstat',
            name='clean_sheet_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstat',
            name='failed_to_score_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstat',
            name='failed_to_score_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstat',
            name='failed_to_score_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstat',
            name='penalties_missed_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstat',
            name='penalties_scored_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstat',
            name='form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teamstat',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='league.league'),
        ),
        migrations.AlterField(
            model_name='teamstat',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='league.season'),
        ),
        migrations.AlterField(
            model_name='teamstat',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='league.team'),
        ),
    ]
