# Generated by Django 5.0.4 on 2024-06-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('league_id', models.IntegerField(primary_key=True, serialize=False)),
                ('league_name', models.CharField(blank=True, max_length=500, null=True)),
                ('league_enName', models.CharField(blank=True, max_length=500, null=True)),
                ('league_faName', models.CharField(blank=True, max_length=500, null=True)),
                ('league_type', models.CharField(blank=True, max_length=50, null=True)),
                ('league_logo', models.URLField(blank=True, null=True)),
                ('league_country', models.JSONField()),
                ('seasons', models.JSONField(blank=True, null=True)),
                ('num_teams', models.IntegerField(blank=True, null=True)),
                ('num_rounds', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
